openapi: 3.1.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  title: "Web crawler"
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /execution:
    get:
      summary: Get a list of all execution IDs.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                description: Array of all execution IDs
                items:
                  type: string
                  format: uuid
  /execution/{executionId}:
    get:
      summary: Get a execution with a given executionID
      parameters:
        - in: path
          name: executionID
          required: true
          description: Execution identifier
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/jon:
              schema:
                $ref: "#/components/schemas/execution"
        "404":
          description: Not found.
    delete:
      summary: Delete an execution with given executionID
      parameters:
        - in: path
          name: executionID
          required: true
          description: Execution identifier
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
        "404":
          description: Not found.


components:
  execution:
    type: object
    description: The execution of crawler on this URL
    properties:
      id:
        type: string
        format: uuid
      startURL:
        type: string
      nodes:
        description: The map of crawled pages as a graph
        type: array
        items:
          type: object
          required:
            - url
            - links
          properties:
            url:
              type: string
            title:
              type: string
            crawlTime:
              type: string
              format: date-time
            links:
              description: Links to pages that are hyperlinked from this page
              type: array
              items:
                type: string
                format: uri
            sourceLinks:
              description: List of website record that crawled this given node.
              type: array
              items:
                type: string
                format: uuid
      
